from enum import Enum

class Name(Enum):
    # GOLEMS
    # WATER_GOLEM = "water_golem"
    # SANDSTONE_GOLEM = "sandstone_golem"
    # TIN_GOLEM = "tin_golem"
    # STONE_GOLEM = "stone_golem"
    # COPPER_GOLEM = "copper_golem"
    # GRANITE_GOLEM = "granite_golem"
    # MUD_GOLEM = "mud_golem"
    # LIMESTONE_GOLEM = "limestone_golem"

    # BUTTONS
    MAKE_STATUE = "make statue"
    DISCOVER_KNOWLEDGE = "discover knowledge"

    # ATRIBUTES
    CHAOS = "chaos"
    CREATIVITY = "creativity"
    JUSTICE = "justice"
    HEALTH = "health"
    MAGIC = "magic"
    COURAGE = "courage"
    DOMINANCE = "dominance"
    HAPPINESS = "happiness"

    # RESOURCES
    MUD = "mud"
    WOOD = "wood"
    WATER = "water"
    STONE = "stone"
    SANDSTONE = "sandstone"
    GRANITE = "granite"
    LIMESTONE = "limestone"
    TIN = "tin"
    COPPER = "copper"

    BRONZE = "bronze"

    IRON = "iron"
    COAL = "coal"
    GOLD = "gold"
    PLATINUM = "platinum"
    CHROME = "chrome"
    ALUMINIUM = "aluminium"
    TITANIUM = "titanium"
    URANIUM = "uranium"
    NICKEL = "nickel"

    FLINT = "flint"
    MEAT = "meat"
    HIDE = "hide"
    CLAY = "clay"
    CHARCOAL = "charcoal"
    STONE_TOOLS = "stone tools"
    POTTERY = "pottery"
    LOG = "log"
    ROPE = "rope"
    DRIED_MEAT = "dried meat"
    PRIMITIVE_FURNACE = "primitive furnace"
    ASH = "ash"
    WOODEN_SPEAR = "wooden spear"
    BOW = "bow"

    # WORKS
    GATHERER = "gatherer"
    #ASTRONOMER = "astronomer"
    LUMBERJACK = "lumberjack"
    HUNTER = "hunter"
    FLINT_KNAPPER = "flint knapper"
    POTTERY_MAKER = "pottery maker"
    CHARCOAL_MAKER = "charcoal maker"
    MINER = "miner"
    TOOL_MAKER = "tool maker"
    BUILDER = "builder"
    SPEAR_MAKER = "spear maker"
    BOWYER = "bowyer"
    MEAT_DRIER = "meat drier"
    ROPE_MAKER = "rope maker"
    FURNACE_OPERATOR = "furnace operator"

    # KNOWLEDGE
    BASIC_HUNTING = "basic hunting"
    FLINT_PROCESSING = "flint processing"
    CLAY_WORKING = "clay working"
    FIRE_CONTROL = "fire control"
    BASIC_MINING = "basic mining"
    BASIC_TOOL_MAKING = "basic tool making"
    FOOD_PRESERVATION = "food preservation"
    LEATHER_WORKING = "leather working"
    SMELTING_PREPARATIONS = "smelting preparations"
    KILN_CONSTRUCTION = "kiln construction"
    BRONZE_SMELTING = "bronze smelting"
    WOOD_CUTTING = "wood cutting"
    PRIMITIVE_WEAPONS = "primitive weapons"
    BOW_MAKING = "bow making"
    ROPE_MAKING = "rope making"
    DRYING_TECHNIQUES = "drying techniques"
    FURNACE_BUILDING = "furnace building"